name: Test Build for iOS

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    name: build for ios
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Flutter Deployment
      uses: jeanluc243/Flutter-Deployment@0.1
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
    - name: build action
      run: flutter build ios
